import Head from "next/head";
import Typography from "@mui/material/Typography";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Amazon clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Typography variant="h1" color="initial">
        Amazon Clone
      </Typography>
    </div>
  );
}
